export type Grade = "A" | "B" | "C" | "D";

export interface StateMatrix {
  loading: boolean;
  empty: boolean;
  error: boolean;
  success: boolean;
  validationFailure: boolean;
  serverFailure: boolean;
  networkError: boolean;
  permissionDenied: boolean;
}

export interface CategoryItem {
  label: string;
  status: "pass" | "fail" | "na";
}

export interface CategoryScore {
  name: string;
  passed: number;
  total: number;
  items: CategoryItem[];
}

export interface ExampleQuality {
  slug: string;
  title: string;
  route: string;
  grade: Grade;
  testCount: number;
  reproducible: boolean;
  stateMatrix: StateMatrix;
  categories: CategoryScore[];
}

export const qualityData: ExampleQuality[] = [
  {
    slug: "auth-flow",
    title: "Auth Flow",
    route: "/login, /signup, /forgot-password",
    grade: "A",
    testCount: 12,
    reproducible: true,
    stateMatrix: {
      loading: true,
      empty: false,
      error: true,
      success: true,
      validationFailure: true,
      serverFailure: true,
      networkError: false,
      permissionDenied: false,
    },
    categories: [
      {
        name: "Accessibility",
        passed: 8,
        total: 10,
        items: [
          { label: "aria-describedby on error fields", status: "pass" },
          { label: "Error state reset on navigation", status: "pass" },
          { label: "Icon buttons have aria-label", status: "pass" },
          { label: "Focus moves to first error on submit", status: "pass" },
          { label: "Password toggle accessible", status: "pass" },
          { label: "Form landmark role", status: "pass" },
          { label: "Color contrast in error states", status: "pass" },
          { label: "Loading state announced to AT", status: "pass" },
          { label: "Skip-to-content link", status: "fail" },
          { label: "High contrast mode support", status: "fail" },
        ],
      },
      {
        name: "Type Safety",
        passed: 9,
        total: 10,
        items: [
          { label: "Zod schema with zodResolver", status: "pass" },
          { label: "Inferred form types via z.infer", status: "pass" },
          { label: "Typed dispatch and selector hooks", status: "pass" },
          { label: "Async thunk properly typed", status: "pass" },
          { label: "rejectWithValue typed", status: "pass" },
          { label: "No implicit any", status: "pass" },
          { label: "Strict null checks", status: "pass" },
          { label: "Component props typed", status: "pass" },
          { label: "API response types", status: "pass" },
          { label: "Discriminated union for auth status", status: "fail" },
        ],
      },
      {
        name: "State Coverage",
        passed: 5,
        total: 8,
        items: [
          { label: "Loading state", status: "pass" },
          { label: "Success state", status: "pass" },
          { label: "Validation error state", status: "pass" },
          { label: "Server error state", status: "pass" },
          { label: "Empty/initial state", status: "pass" },
          { label: "Network error state", status: "fail" },
          { label: "Rate limiting state", status: "fail" },
          { label: "Resend/retry flow", status: "fail" },
        ],
      },
      {
        name: "Consistency",
        passed: 9,
        total: 10,
        items: [
          { label: "Follows project directory structure", status: "pass" },
          { label: "Uses shared UI components", status: "pass" },
          { label: "Consistent naming conventions", status: "pass" },
          { label: "Follows Redux slice pattern", status: "pass" },
          { label: "Uses project form pattern", status: "pass" },
          { label: "Error handling matches project style", status: "pass" },
          { label: "Uses cn() for conditional classes", status: "pass" },
          { label: "Semantic token usage", status: "pass" },
          { label: "Follows file export pattern", status: "pass" },
          { label: "Uses project toast pattern", status: "fail" },
        ],
      },
    ],
  },
  {
    slug: "dashboard-table",
    title: "Dashboard Table",
    route: "/dashboard",
    grade: "A",
    testCount: 5,
    reproducible: true,
    stateMatrix: {
      loading: true,
      empty: true,
      error: false,
      success: true,
      validationFailure: false,
      serverFailure: false,
      networkError: false,
      permissionDenied: false,
    },
    categories: [
      {
        name: "Accessibility",
        passed: 7,
        total: 10,
        items: [
          { label: "aria-sort on sortable columns", status: "pass" },
          { label: "Row-specific checkbox labels", status: "pass" },
          { label: "Empty state announced to AT", status: "pass" },
          { label: "Semantic table elements", status: "pass" },
          { label: "Keyboard navigation", status: "pass" },
          { label: "Focus management on page change", status: "pass" },
          { label: "Sort direction announced", status: "pass" },
          { label: "Bulk action confirmation dialog", status: "fail" },
          { label: "Filter change announced to AT", status: "fail" },
          { label: "Pagination state announced", status: "fail" },
        ],
      },
      {
        name: "Type Safety",
        passed: 8,
        total: 10,
        items: [
          { label: "Column definitions typed", status: "pass" },
          { label: "Generic DataTable component", status: "pass" },
          { label: "Typed Redux slice", status: "pass" },
          { label: "Query parameter types", status: "pass" },
          { label: "Mock data typed", status: "pass" },
          { label: "Cell renderer types", status: "pass" },
          { label: "Row selection typed", status: "pass" },
          { label: "Pagination state typed", status: "pass" },
          { label: "Role badge variant cast-free", status: "fail" },
          { label: "Status config cast-free", status: "fail" },
        ],
      },
      {
        name: "State Coverage",
        passed: 5,
        total: 10,
        items: [
          { label: "Loading state", status: "pass" },
          { label: "Empty (no data) state", status: "pass" },
          { label: "Empty (no filter results) state", status: "pass" },
          { label: "Success with data", status: "pass" },
          { label: "Pagination state", status: "pass" },
          { label: "Server error state", status: "fail" },
          { label: "Network error state", status: "fail" },
          { label: "Stale data during refetch", status: "fail" },
          { label: "Bulk action in progress", status: "fail" },
          { label: "Permission denied state", status: "fail" },
        ],
      },
      {
        name: "Consistency",
        passed: 9,
        total: 10,
        items: [
          { label: "Follows project directory structure", status: "pass" },
          { label: "Uses shared UI components", status: "pass" },
          { label: "Consistent naming conventions", status: "pass" },
          { label: "Follows Redux slice pattern", status: "pass" },
          { label: "Uses TanStack Table pattern", status: "pass" },
          { label: "Error handling matches project style", status: "pass" },
          { label: "Uses cn() for conditional classes", status: "pass" },
          { label: "Semantic token usage", status: "pass" },
          { label: "Follows file export pattern", status: "pass" },
          { label: "Uses project loading pattern", status: "fail" },
        ],
      },
    ],
  },
  {
    slug: "settings-page",
    title: "Settings Page",
    route: "/settings",
    grade: "A",
    testCount: 7,
    reproducible: true,
    stateMatrix: {
      loading: true,
      empty: false,
      error: true,
      success: true,
      validationFailure: true,
      serverFailure: true,
      networkError: false,
      permissionDenied: false,
    },
    categories: [
      {
        name: "Accessibility",
        passed: 8,
        total: 10,
        items: [
          { label: "aria-describedby on error fields", status: "pass" },
          { label: "Form labels on all inputs", status: "pass" },
          { label: "Disabled state communicated to AT", status: "pass" },
          { label: "Error alerts use role=alert", status: "pass" },
          { label: "Keyboard-accessible tabs", status: "pass" },
          { label: "Checkbox has aria-label", status: "pass" },
          { label: "Loading skeleton announced", status: "pass" },
          { label: "Focus management on tab switch", status: "pass" },
          { label: "Toggle switches have ARIA role", status: "fail" },
          { label: "High contrast mode support", status: "fail" },
        ],
      },
      {
        name: "Type Safety",
        passed: 9,
        total: 10,
        items: [
          { label: "Zod schema with zodResolver", status: "pass" },
          { label: "Inferred form types via z.infer", status: "pass" },
          { label: "Typed dispatch and selector hooks", status: "pass" },
          { label: "Async thunk properly typed", status: "pass" },
          { label: "Slice state interface defined", status: "pass" },
          { label: "Notification preferences typed", status: "pass" },
          { label: "No implicit any", status: "pass" },
          { label: "Component props typed", status: "pass" },
          { label: "Optimistic update action typed", status: "pass" },
          { label: "Discriminated union for save status", status: "fail" },
        ],
      },
      {
        name: "State Coverage",
        passed: 6,
        total: 8,
        items: [
          { label: "Idle state", status: "pass" },
          { label: "Loading state", status: "pass" },
          { label: "Saving state", status: "pass" },
          { label: "Save success state", status: "pass" },
          { label: "Save error state", status: "pass" },
          { label: "Dirty state tracking", status: "pass" },
          { label: "Network error state", status: "fail" },
          { label: "Permission denied state", status: "fail" },
        ],
      },
      {
        name: "Consistency",
        passed: 9,
        total: 10,
        items: [
          { label: "Follows project directory structure", status: "pass" },
          { label: "Uses shared UI components", status: "pass" },
          { label: "Consistent naming conventions", status: "pass" },
          { label: "Follows Redux slice pattern", status: "pass" },
          { label: "Uses project form pattern", status: "pass" },
          { label: "Error handling matches project style", status: "pass" },
          { label: "Uses cn() for conditional classes", status: "pass" },
          { label: "Semantic token usage", status: "pass" },
          { label: "Follows file export pattern", status: "pass" },
          { label: "Uses project toast pattern", status: "fail" },
        ],
      },
    ],
  },
  {
    slug: "multi-step-wizard",
    title: "Multi-step Wizard",
    route: "/wizard",
    grade: "A",
    testCount: 8,
    reproducible: true,
    stateMatrix: {
      loading: false,
      empty: false,
      error: true,
      success: true,
      validationFailure: true,
      serverFailure: true,
      networkError: false,
      permissionDenied: false,
    },
    categories: [
      {
        name: "Accessibility",
        passed: 7,
        total: 10,
        items: [
          { label: "Form labels on all inputs", status: "pass" },
          { label: "Plan cards use role=radio", status: "pass" },
          { label: "Plan cards use aria-checked", status: "pass" },
          { label: "Error alerts use role=alert", status: "pass" },
          { label: "Keyboard navigation for steps", status: "pass" },
          { label: "Focus management on step change", status: "pass" },
          { label: "Edit buttons accessible", status: "pass" },
          { label: "Step indicator has ARIA attributes", status: "fail" },
          { label: "Step transitions announced to AT", status: "fail" },
          { label: "High contrast mode support", status: "fail" },
        ],
      },
      {
        name: "Type Safety",
        passed: 8,
        total: 10,
        items: [
          { label: "Zod schema with zodResolver", status: "pass" },
          { label: "Inferred form types via z.infer", status: "pass" },
          { label: "Typed dispatch and selector hooks", status: "pass" },
          { label: "Async thunk properly typed", status: "pass" },
          { label: "Slice state interface defined", status: "pass" },
          { label: "Plan type as union literal", status: "pass" },
          { label: "No implicit any", status: "pass" },
          { label: "Component props typed", status: "pass" },
          { label: "Step state discriminated union", status: "fail" },
          { label: "goToStep bounds checked at type level", status: "fail" },
        ],
      },
      {
        name: "State Coverage",
        passed: 6,
        total: 10,
        items: [
          { label: "Idle state", status: "pass" },
          { label: "Validating state", status: "pass" },
          { label: "Valid state", status: "pass" },
          { label: "Submit loading state", status: "pass" },
          { label: "Submit success state", status: "pass" },
          { label: "Submit error state", status: "pass" },
          { label: "Network error state", status: "fail" },
          { label: "Save draft state", status: "fail" },
          { label: "Timeout state", status: "fail" },
          { label: "Session expired state", status: "fail" },
        ],
      },
      {
        name: "Consistency",
        passed: 9,
        total: 10,
        items: [
          { label: "Follows project directory structure", status: "pass" },
          { label: "Uses shared UI components", status: "pass" },
          { label: "Consistent naming conventions", status: "pass" },
          { label: "Follows Redux slice pattern", status: "pass" },
          { label: "Uses project form pattern", status: "pass" },
          { label: "Error handling matches project style", status: "pass" },
          { label: "Uses cn() for conditional classes", status: "pass" },
          { label: "Semantic token usage", status: "pass" },
          { label: "Follows file export pattern", status: "pass" },
          { label: "Uses project loading pattern", status: "fail" },
        ],
      },
    ],
  },
  {
    slug: "optimistic-crud",
    title: "Optimistic CRUD",
    route: "/items",
    grade: "A",
    testCount: 14,
    reproducible: true,
    stateMatrix: {
      loading: true,
      empty: true,
      error: true,
      success: true,
      validationFailure: true,
      serverFailure: true,
      networkError: false,
      permissionDenied: false,
    },
    categories: [
      {
        name: "Accessibility",
        passed: 7,
        total: 10,
        items: [
          { label: "Error alerts use role=alert", status: "pass" },
          { label: "Keyboard-accessible table rows", status: "pass" },
          { label: "Icon buttons have aria-label", status: "pass" },
          { label: "Empty state announced to AT", status: "pass" },
          { label: "Form labels on all inputs", status: "pass" },
          { label: "Loading skeleton announced", status: "pass" },
          { label: "Delete confirmation dialog accessible", status: "pass" },
          { label: "Dialog focus trap", status: "fail" },
          { label: "Confirmation needs proper ARIA", status: "fail" },
          { label: "High contrast mode support", status: "fail" },
        ],
      },
      {
        name: "Type Safety",
        passed: 9,
        total: 10,
        items: [
          { label: "Task interface defined", status: "pass" },
          { label: "Typed dispatch and selector hooks", status: "pass" },
          { label: "Async thunks properly typed", status: "pass" },
          { label: "rejectWithValue typed", status: "pass" },
          { label: "PayloadAction typed for reducers", status: "pass" },
          { label: "No implicit any", status: "pass" },
          { label: "Zod schema with zodResolver", status: "pass" },
          { label: "Priority as union literal", status: "pass" },
          { label: "Component props typed", status: "pass" },
          { label: "Discriminated union for task status", status: "fail" },
        ],
      },
      {
        name: "State Coverage",
        passed: 7,
        total: 10,
        items: [
          { label: "Idle state", status: "pass" },
          { label: "Loading state", status: "pass" },
          { label: "Create optimistic + rollback", status: "pass" },
          { label: "Edit optimistic + rollback", status: "pass" },
          { label: "Delete optimistic + rollback", status: "pass" },
          { label: "Empty state with CTA", status: "pass" },
          { label: "Error state with retry", status: "pass" },
          { label: "Network error state", status: "fail" },
          { label: "Bulk operations", status: "fail" },
          { label: "Undo after rollback", status: "fail" },
        ],
      },
      {
        name: "Consistency",
        passed: 9,
        total: 10,
        items: [
          { label: "Follows project directory structure", status: "pass" },
          { label: "Uses shared UI components", status: "pass" },
          { label: "Consistent naming conventions", status: "pass" },
          { label: "Follows Redux slice pattern", status: "pass" },
          { label: "Uses project form pattern", status: "pass" },
          { label: "Error handling matches project style", status: "pass" },
          { label: "Uses cn() for conditional classes", status: "pass" },
          { label: "Semantic token usage", status: "pass" },
          { label: "Follows file export pattern", status: "pass" },
          { label: "Uses project toast pattern", status: "fail" },
        ],
      },
    ],
  },
  {
    slug: "file-upload",
    title: "File Upload",
    route: "/upload",
    grade: "A",
    testCount: 17,
    reproducible: true,
    stateMatrix: {
      loading: true,
      empty: true,
      error: true,
      success: true,
      validationFailure: true,
      serverFailure: true,
      networkError: false,
      permissionDenied: false,
    },
    categories: [
      {
        name: "Accessibility",
        passed: 6,
        total: 10,
        items: [
          { label: "Upload zone has role=button", status: "pass" },
          { label: "Keyboard activation with Enter/Space", status: "pass" },
          { label: "Retry buttons have aria-label", status: "pass" },
          { label: "Remove buttons have aria-label", status: "pass" },
          { label: "Image previews have alt text", status: "pass" },
          { label: "Disabled state uses aria-disabled", status: "pass" },
          { label: "Drag zone needs aria-label improvement", status: "fail" },
          { label: "Progress needs aria-valuemin/max", status: "fail" },
          { label: "File list needs group label", status: "fail" },
          { label: "High contrast mode support", status: "fail" },
        ],
      },
      {
        name: "Type Safety",
        passed: 8,
        total: 10,
        items: [
          { label: "FileUpload interface defined", status: "pass" },
          { label: "Typed dispatch and selector hooks", status: "pass" },
          { label: "Async thunks properly typed", status: "pass" },
          { label: "rejectWithValue typed", status: "pass" },
          { label: "PayloadAction typed for reducers", status: "pass" },
          { label: "No implicit any", status: "pass" },
          { label: "Component props typed", status: "pass" },
          { label: "File constants typed", status: "pass" },
          { label: "File API types are loose", status: "fail" },
          { label: "Discriminated union for upload status", status: "fail" },
        ],
      },
      {
        name: "State Coverage",
        passed: 8,
        total: 10,
        items: [
          { label: "Idle state", status: "pass" },
          { label: "Dragging over state", status: "pass" },
          { label: "Uploading with progress", status: "pass" },
          { label: "Complete state", status: "pass" },
          { label: "Failed state with retry", status: "pass" },
          { label: "Validation rejection", status: "pass" },
          { label: "File count limit reached", status: "pass" },
          { label: "Empty state", status: "pass" },
          { label: "Offline state", status: "fail" },
          { label: "Quota exceeded state", status: "fail" },
        ],
      },
      {
        name: "Consistency",
        passed: 8,
        total: 10,
        items: [
          { label: "Follows project directory structure", status: "pass" },
          { label: "Uses shared UI components", status: "pass" },
          { label: "Consistent naming conventions", status: "pass" },
          { label: "Follows Redux slice pattern", status: "pass" },
          { label: "Error handling matches project style", status: "pass" },
          { label: "Uses cn() for conditional classes", status: "pass" },
          { label: "Semantic token usage", status: "pass" },
          { label: "Follows file export pattern", status: "pass" },
          { label: "Uses project toast pattern", status: "fail" },
          { label: "Uses project loading pattern", status: "fail" },
        ],
      },
    ],
  },
];
